title: Wizards of Lua
description: The Art of Spell Crafting
theme: jekyll-theme-midnight
encoding: "utf-8"
show_header: true
github:
  project_url: https://github.com/wizards-of-lua/wizards-of-lua
show_dir_listing: false
defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      type: modules
    values:
      layout: module
  - scope:
      type: tutorials
    values:
      layout: tutorial
collections:
  modules:
    output: true
    permalink: /modules/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
