title: Wizards of Lua
theme: jekyll-theme-midnight
defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: ""
      type: modules
    values:
      layout: page
collections:
  modules:
    output: true
    permalink: /modules-xxx/:path/
