title: Wizards of Lua
theme: jekyll-theme-midnight
#baseurl: /webpage
defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      type: modules
    values:
      layout: default
collections:
  modules:
    output: true
    permalink: /modules/:path/
